# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

screen=\
	STEADFAST \
	<profile> \
	[EFFECTS] \
	[WATER] \
	[ATMOSPHERE_CLOUDS] \
	[LIGHTING] \
	[DEVELOPMENT]

screen.EFFECTS=\
	GODRAYS \
	NIGHT_DESATURATION_EFFECT \
	TONEMAP \
	SATURATED_TONEMAP \
	WAVING_FOLIAGE

screen.WATER=\
	FANCY_TRANSLUCENTS \
	[WATER_WAVES] \
	SCREENSPACE_REFLECTIONS \
	SCREENSPACE_REFRACTION \
	VANILLA_ISH_WATER \
	WATER_CHARACTER \
	DARK_UNDERWATER \
	WATER_ABSORPTION_METHOD \
	WATER_CAUSTICS \
	NUM_CAUSTICS \
	WATER_CAUSTICS_DISTANCE

screen.WATER_WAVES=\
	WATER_SURFACE \
	WATER_AA \
	WATER_PARALLAX \
	WATER_PARALLAX_DISTANCE \
	NUM_CRESTS \
	NUM_RIPPLES

screen.ATMOSPHERE_CLOUDS=\
	ATMOSPHERE_MODEL \
	[LEGACY_ATMOSPHERE] \
	PLANAR_CLOUD_LAYERS \
	VANILLA_CLOUDS \
	BORDER_FOG \
	ATMOSPHERE_FOG_STRENGTH_NOON

screen.LEGACY_ATMOSPHERE=\
	DAY_ATMOSPHERE \
	NIGHT_ATMOSPHERE \
	HARDER_HORIZON_DAY \
	HARDER_HORIZON_NIGHT

screen.LIGHTING=\
	DAY_SKY_LIGHTING \
	NIGHT_SKY_LIGHTING \
	ORANGER_BLOCKLIGHT \
	HELD_BLOCK_LIGHTING \
	REAL_TIME_SHADOWS \
	REAL_TIME_ENTITY_SHADOWS \
	REAL_TIME_BLOCK_ENTITY_SHADOWS \
	SHADOW_DISTORT_FACTOR \
	SOFTER_SHADOWS \
	SHADOW_SOFTNESS \
	shadowMapResolution \
	shadowDistance \
	DIRECTIONAL_SKYLIGHT_SHADING

screen.DEVELOPMENT=\
	DEBUG \
	SURFACE_COLORS \
	FREEZE_ANIMATION_TIMER \
	PREFER_FDM_GRADIENT \
	*

sliders=\
	shadowDistance \
	WATER_CAUSTICS_DISTANCE \
	NUM_CAUSTICS \
	PLANAR_CLOUD_LAYERS \
	DARK_UNDERWATER \
	NUM_CRESTS \
	NUM_RIPPLES \
	WATER_PARALLAX_DISTANCE \
	WATER_AA \
	ATMOSPHERE_FOG_STRENGTH_NOON \
	shadowMapResolution \
	SHADOW_DISTORT_FACTOR \
	SHADOW_SOFTNESS
