# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

screen=\
	STEADFAST \
	<profile> \
	[EFFECTS] \
	[WATER] \
	[ATMOSPHERE_CLOUDS] \
	[LIGHTING] \
	[MATERIALS] \
	[DEVELOPMENT]

screen.EFFECTS=\
	GODRAYS \
	NIGHT_DESATURATION_EFFECT \
	TONEMAP \
	SATURATED_TONEMAP \
	WAVING_FOLIAGE

screen.WATER=\
	SCREENSPACE_REFLECTIONS \
	SCREENSPACE_REFRACTION \
	WATER_SURFACE \
	[WATER_SURFACE_NOISE] \
	FANCY_TRANSLUCENTS \
	VANILLA_ISH_WATER \
	WATER_CAUSTICS \
	NUM_CAUSTICS \
	WATER_CAUSTICS_DISTANCE \
	WATER_CHARACTER

screen.WATER_SURFACE_NOISE=\
	WATER_PARALLAX \
	WATER_PARALLAX_DISTANCE \
	WATER_AA \
	NUM_CRESTS \
	NUM_RIPPLES

screen.ATMOSPHERE_CLOUDS=\
	PLANAR_CLOUD_LAYERS \
	VANILLA_CLOUDS \
	BORDER_FOG \
	ATMOSPHERE_FOG_STRENGTH_NOON \
	ATMOSPHERE_MODEL \
	[LEGACY_ATMOSPHERE]

screen.LEGACY_ATMOSPHERE=\
	DAY_ATMOSPHERE \
	NIGHT_ATMOSPHERE \
	HARDER_HORIZON_DAY \
	HARDER_HORIZON_NIGHT

screen.LIGHTING=\
	[REAL_TIME_SHADOWS] \
	DIRECTIONAL_SKYLIGHT_SHADING \
	DAY_SKY_LIGHTING \
	NIGHT_SKY_LIGHTING \
	ambientOcclusionLevel \
	DIRECT_LIGHT_AMBIENT_OCCLUSION \
	BLOCKLIGHT_COLOR \
	HELD_LIGHT_COLOR \
	BLOCKLIGHT_LUMINANCE \
	LIGHT_CUSTOM_R \
	LIGHT_CUSTOM_G \
	LIGHT_CUSTOM_B \
	HELD_BLOCK_LIGHTING

screen.REAL_TIME_SHADOWS=\
	REAL_TIME_SHADOWS \
	shadowMapResolution \
	REAL_TIME_ENTITY_SHADOWS \
	REAL_TIME_BLOCK_ENTITY_SHADOWS \
	shadowDistance \
	SHADOW_SOFTNESS \
	SOFTER_SHADOWS \
	SHADOW_DISTORT_FACTOR

screen.MATERIALS=\
	[RESOURCE_PACK_MATERIALS] \
	EMISSIVE_DETECTION

screen.RESOURCE_PACK_MATERIALS=\
	PBR_NORMAL_MAPPING \
	LABPBR_AMBIENT_OCCLUSION \

screen.DEVELOPMENT=\
	DEBUG \
	FREEZE_ANIMATION_TIMER \
	PREFER_FDM_GRADIENT \
	*

sliders=\
	ambientOcclusionLevel \
	shadowDistance \
	WATER_CAUSTICS_DISTANCE \
	NUM_CAUSTICS \
	PLANAR_CLOUD_LAYERS \
	BLOCKLIGHT_COLOR \
	HELD_LIGHT_COLOR \
	BLOCKLIGHT_LUMINANCE \
	LIGHT_CUSTOM_R \
	LIGHT_CUSTOM_G \
	LIGHT_CUSTOM_B
