# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Disabled by default on Iris, but let's just be certain. We do our own
# directional lighting and have no need for Minecraft's directional lighting.
oldLighting=false

# This moves the ambient occlusion value to the alpha channel of the vertex
# color, which enables us to handle it separately from the color itself.
separateAo=true

# Vanilla draws a water texture over the screen, which is super ugly with
# shaders. Disable it.
underwaterOverlay=false

# Disable programs when we don't have the corresponding effect, saves a bit of
# performance.
program.composite.enabled=GODRAYS
program.deferred1.enabled=ROUGH_REFRACTION

# Iris 1.5 does not support this more complex condition, but as it is an
# optimization, it does not matter.
program.deferred.enabled=SCREENSPACE_REFLECTIONS || SCREENSPACE_REFRACTION || WATER_ABSORPTION_METHOD == REFRACTION_ASSISTED

#ifndef REAL_TIME_ENTITY_SHADOWS
	shadowEntities=false

	# Still cast shadows from the player
	shadowPlayer=true
#endif

#ifndef REAL_TIME_BLOCK_ENTITY_SHADOWS
	# Note: Block entities do not seem to respect the reduced entity render
	# distance, so therefore they can be very costly.
	shadowBlockEntities=false
#endif

#ifndef VANILLA_CLOUDS
	# Disable default clouds when planar clouds are on.
	clouds=off
#endif

# Allows drawing translucent entities (like slimes) after the deferred pass runs,
# so that the background they blend against has fog properly applied.
separateEntityDraws=false

# Render godrays buffer at half resolution
# Keep this in sync with the windowToScreenHalf custom uniform.
size.buffer.colortex1=0.5 0.5

# Downsampled refraction/reflection buffer for rough refraction (blur).
# Keep this in sync with the windowToScreenHalf custom uniform.
size.buffer.colortex6=0.5 0.5

#ifdef FANCY_TRANSLUCENTS
	# Colors: Premultiplied alpha blending mode
	# Alpha: Do not change the color
	blend.gbuffers_water=ONE ONE_MINUS_SRC_ALPHA ZERO ONE
	blend.dh_water=ONE ONE_MINUS_SRC_ALPHA ZERO ONE

	# Because of our modified blending mode, alpha tests on the fragment output
	# are not valid. Because Minecraft 1.21.11+ uses cutout on the translucent
	# terrain pass for tripwire, we hardcode the alphaTestRef separately for it.
	alphaTest.gbuffers_water=off
	alphaTest.dh_water=off
#endif

# This unconditionally excludes Distant Horizons terrain from the shadow pass.
# Including distant terrain in the shadow pass does not work well with our
# single shadow map cascade, and both rendering distant terrain into the shadow
# map and sampling the shadow map while rendering distant terrain are extremely
# expensive.
#
# Our fallback lightmap shadows look better at this distance, and a better
# approach is screen-space shadows or any other non-shadowmap rendering method.
dhShadow.enabled=false
