# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# WIP new visual style
profile.MINISHITA_HIGH= \
	\
	GODRAYS NIGHT_DESATURATION_EFFECT \
	\
	!VANILLA_ISH_WATER FANCY_TRANSLUCENTS WATER_ABSORPTION_METHOD:REFRACTION_ASSISTED \
	SCREENSPACE_REFRACTION SCREENSPACE_REFLECTIONS \
	WATER_SURFACE:NOISE \
	WATER_PARALLAX WATER_PARALLAX_DISTANCE:48.0 \
	WATER_CAUSTICS WATER_CAUSTICS_DISTANCE:48.0 \
	\
	shadowMapResolution:1536 \
	shadowDistance:160 \
	REAL_TIME_SHADOWS \
	REAL_TIME_ENTITY_SHADOWS \
	!REAL_TIME_BLOCK_ENTITY_SHADOWS \
	MINISHITA_LIGHTING \
	DIRECTIONAL_SKYLIGHT_SHADING \
	BLOCKLIGHT_COLOR:BLACKBODY_3000K \
	HELD_LIGHT_COLOR:BLACKBODY_3000K \
	HELD_BLOCK_LIGHTING \
	\
	ATMOSPHERE_MODEL:MINISHITA TONEMAP:TONEMAP_UCHIMURA \
	\
	ATMOSPHERE_FOG_STRENGTH_NOON:0.5 BORDER_FOG \
	\
	PLANAR_CLOUD_LAYERS:0 \
	!VANILLA_CLOUDS

profile.MINISHITA_MEDIUM=profile.MINISHITA_HIGH !GODRAYS WATER_PARALLAX_DISTANCE:32.0 WATER_CAUSTICS_DISTANCE:32.0 shadowDistance:112
profile.MINISHITA_LOW=profile.MINISHITA_MEDIUM WATER_SURFACE:BASIC !WATER_CAUSTICS !SCREENSPACE_REFRACTION !SCREENSPACE_REFLECTIONS shadowMapResolution:1024 shadowDistance:80 !REAL_TIME_ENTITY_SHADOWS
profile.MINISHITA_TOASTER=profile.MINISHITA_LOW !REAL_TIME_SHADOWS

# The flagship profile of Steadfast. Colorful yet cozy, Paragon blends a variety of visual styles and is the very best that Steadfast has to offer.
profile.PARAGON_HIGH=profile.SEMI_NATURAL_HIGH NIGHT_SKY_LIGHTING:FANTASY NIGHT_ATMOSPHERE:FANTASY !HARDER_HORIZON_NIGHT !NIGHT_DESATURATION_EFFECT
profile.PARAGON_MEDIUM=profile.PARAGON_HIGH !GODRAYS WATER_PARALLAX_DISTANCE:32.0 WATER_CAUSTICS_DISTANCE:32.0 shadowDistance:112
profile.PARAGON_LOW=profile.PARAGON_MEDIUM WATER_SURFACE:BASIC !WATER_CAUSTICS !SCREENSPACE_REFRACTION !SCREENSPACE_REFLECTIONS PLANAR_CLOUD_LAYERS:1 shadowMapResolution:1024 shadowDistance:80 !REAL_TIME_ENTITY_SHADOWS
profile.PARAGON_TOASTER=profile.PARAGON_LOW !REAL_TIME_SHADOWS

# Base Fantasy style.
profile.FANTASY_HIGH= \
	\
	GODRAYS !NIGHT_DESATURATION_EFFECT \
	\
	!VANILLA_ISH_WATER FANCY_TRANSLUCENTS WATER_ABSORPTION_METHOD:REFRACTION_ASSISTED \
	SCREENSPACE_REFRACTION SCREENSPACE_REFLECTIONS \
	WATER_SURFACE:NOISE \
	WATER_PARALLAX WATER_PARALLAX_DISTANCE:48.0 \
	WATER_CAUSTICS WATER_CAUSTICS_DISTANCE:48.0 \
	\
	shadowMapResolution:1536 \
	shadowDistance:160 \
	REAL_TIME_SHADOWS \
	REAL_TIME_ENTITY_SHADOWS \
	!REAL_TIME_BLOCK_ENTITY_SHADOWS \
	DAY_SKY_LIGHTING:FANTASY NIGHT_SKY_LIGHTING:FANTASY !MINISHITA_LIGHTING \
	DIRECTIONAL_SKYLIGHT_SHADING \
	BLOCKLIGHT_COLOR:BLACKBODY_3000K \
	HELD_LIGHT_COLOR:BLACKBODY_3000K \
	HELD_BLOCK_LIGHTING \
	\
	DAY_ATMOSPHERE:FANTASY NIGHT_ATMOSPHERE:FANTASY \
	!HARDER_HORIZON_DAY !HARDER_HORIZON_NIGHT \
	ATMOSPHERE_MODEL:GRADIENT TONEMAP:TONEMAP_UNCHARTED2 \
	\
	ATMOSPHERE_FOG_STRENGTH_NOON:1.0 BORDER_FOG \
	\
	PLANAR_CLOUD_LAYERS:0 \
	!VANILLA_CLOUDS

# In Fantasy, the godrays are somewhat more impactful to the appearance of the shader.
# The more basic water surface is actually mostly fine so we switch to that and turn off
# refraction to save a decent amount of performance hit.
profile.FANTASY_MEDIUM=profile.FANTASY_HIGH WATER_SURFACE:BASIC !WATER_CAUSTICS !SCREENSPACE_REFRACTION WATER_PARALLAX_DISTANCE:16.0 WATER_CAUSTICS_DISTANCE:24.0 shadowDistance:112

# Go to the lowest performance impact while still maintaining the basic lighting system
# with shadow mapping as well as a basic water surface.
profile.FANTASY_LOW=profile.FANTASY_MEDIUM !SCREENSPACE_REFLECTIONS !GODRAYS shadowMapResolution:1024 shadowDistance:80 !REAL_TIME_ENTITY_SHADOWS

# Same as Low, but without any shadow mapping.
profile.FANTASY_TOASTER=profile.FANTASY_LOW !REAL_TIME_SHADOWS

# Base Semi-Natural style.
profile.SEMI_NATURAL_HIGH= \
	\
	GODRAYS NIGHT_DESATURATION_EFFECT \
	\
	!VANILLA_ISH_WATER FANCY_TRANSLUCENTS WATER_ABSORPTION_METHOD:REFRACTION_ASSISTED \
	SCREENSPACE_REFRACTION SCREENSPACE_REFLECTIONS \
	WATER_SURFACE:NOISE \
	WATER_PARALLAX WATER_PARALLAX_DISTANCE:48.0 \
	WATER_CAUSTICS WATER_CAUSTICS_DISTANCE:48.0 \
	\
	shadowMapResolution:1536 \
	shadowDistance:160 \
	REAL_TIME_SHADOWS \
	REAL_TIME_ENTITY_SHADOWS \
	!REAL_TIME_BLOCK_ENTITY_SHADOWS \
	DAY_SKY_LIGHTING:SEMI_NATURAL NIGHT_SKY_LIGHTING:SEMI_NATURA !MINISHITA_LIGHTING \
	DIRECTIONAL_SKYLIGHT_SHADING \
	BLOCKLIGHT_COLOR:BLACKBODY_2000K \
	HELD_LIGHT_COLOR:BLACKBODY_2000K \
	HELD_BLOCK_LIGHTING \
	\
	DAY_ATMOSPHERE:SEMI_NATURAL NIGHT_ATMOSPHERE:SEMI_NATURAL \
	HARDER_HORIZON_DAY HARDER_HORIZON_NIGHT \
	ATMOSPHERE_MODEL:GRADIENT TONEMAP:TONEMAP_UNCHARTED2 \
	\
	ATMOSPHERE_FOG_STRENGTH_NOON:0.5 BORDER_FOG \
	\
	PLANAR_CLOUD_LAYERS:2 \
	!VANILLA_CLOUDS


# In Semi-Natural, the water appearance is extremely impactful to the overall appearance of the shader.
# Godrays are surprisingly expensive (being our only post-process effect right now...) so if we are
# willing to drop them, we can (for almost the same performance hit) keep the high-quality parallax
# water with refraction and reflections.
profile.SEMI_NATURAL_MEDIUM=profile.SEMI_NATURAL_HIGH !GODRAYS WATER_PARALLAX_DISTANCE:32.0 WATER_CAUSTICS_DISTANCE:32.0 shadowDistance:112

# Go to the lowest performance impact while still maintaining the basic lighting system
# with shadow mapping as well as a basic water surface.
profile.SEMI_NATURAL_LOW=profile.SEMI_NATURAL_MEDIUM WATER_SURFACE:BASIC !WATER_CAUSTICS !SCREENSPACE_REFRACTION !SCREENSPACE_REFLECTIONS PLANAR_CLOUD_LAYERS:1 shadowMapResolution:1024 shadowDistance:80 !REAL_TIME_ENTITY_SHADOWS

# Same as Low, but without any shadow mapping.
profile.SEMI_NATURAL_TOASTER=profile.SEMI_NATURAL_LOW !REAL_TIME_SHADOWS

# Retro has a pretty low performance impact due to the vanilla water surface, but we still have two
# profiles just to disable godrays as essentially the only post process effect.
profile.RETRO_MEDIUM= \
	\
	GODRAYS !NIGHT_DESATURATION_EFFECT \
	\
	VANILLA_ISH_WATER !FANCY_TRANSLUCENTS WATER_ABSORPTION_METHOD:NO_ABSORPTION \
	!SCREENSPACE_REFRACTION !SCREENSPACE_REFLECTIONS \
	WATER_SURFACE:BASIC \
	!WATER_PARALLAX WATER_PARALLAX_DISTANCE:8.0 \
	!WATER_CAUSTICS \
	\
	shadowMapResolution:1536 \
	shadowDistance:112 \
	REAL_TIME_SHADOWS \
	REAL_TIME_ENTITY_SHADOWS \
	!REAL_TIME_BLOCK_ENTITY_SHADOWS \
	DAY_SKY_LIGHTING:RETRO NIGHT_SKY_LIGHTING:RETRO !MINISHITA_LIGHTING \
	!DIRECTIONAL_SKYLIGHT_SHADING \
	BLOCKLIGHT_COLOR:BLACKBODY_3000K \
	HELD_LIGHT_COLOR:BLACKBODY_3000K \
	HELD_BLOCK_LIGHTING \
	\
	DAY_ATMOSPHERE:RETRO NIGHT_ATMOSPHERE:RETRO \
	!HARDER_HORIZON_DAY !HARDER_HORIZON_NIGHT \
	ATMOSPHERE_MODEL:GRADIENT TONEMAP:TONEMAP_UNCHARTED2 \
	\
	ATMOSPHERE_FOG_STRENGTH_NOON:1.0 BORDER_FOG \
	\
	PLANAR_CLOUD_LAYERS:0 \
	VANILLA_CLOUDS

# As promised, disable the godrays on the lowest setting.
profile.RETRO_LOW=profile.RETRO_MEDIUM !GODRAYS shadowMapResolution:1024 shadowDistance:80 !REAL_TIME_ENTITY_SHADOWS

# Same as Low, but without any shadow mapping.
profile.RETRO_TOASTER=profile.RETRO_LOW !REAL_TIME_SHADOWS
