// Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
// Copyright (C) 2026 coderbot
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
import java.util.Arrays;
import java.util.stream.Collectors;

String stretchUniform(String name, NoiseWave wave) {
	var s = wave.stretch();

	return "uniform.vec3.causticsStretch" + name +
		"=vec3(" + s.scaleX() + "," + s.scaleY() + "," + s.shear() + ")";
}

String scaleUniform(String name, Caustic caustic) {
	var scroll = caustic.wave().scroll();

	return "uniform.vec4.causticsScale" + name +
		"=vec4(" +
			"causticsTimeSeconds * " + scroll.x() +
			", causticsTimeSeconds * " + scroll.y() +
			"," + ((float) caustic.exponent()) +
			"," + ((float) caustic.logMagnitude()) + ")";
}

static final String header = """
# Generated by CausticIrisUniforms.java

#ifdef FREEZE_ANIMATION_TIMER
	variable.float.causticsTimeSeconds=500.0
#else
	variable.float.causticsTimeSeconds=frameTimeCounter
#endif
""";

void main() {
	IO.println(header);

	for (int i = 0; i < Caustic.CAUSTICS.length; i++) {
		Caustic caustic = Caustic.CAUSTICS[i];
		IO.println(stretchUniform(Integer.toString(i), caustic.wave()));
		IO.println(scaleUniform(Integer.toString(i), caustic));
	}
}
