// Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
// Copyright (C) 2026 coderbot
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
import java.util.Arrays;
import java.util.stream.Collectors;

String scrollUniform(String name, NoiseWave.Scroll xy, NoiseWave.Scroll zw) {
	return "uniform.vec4.waterScroll" + name + "=vec4(" +
		"waterTimeSeconds * " + xy.x() +
		", waterTimeSeconds * " + xy.y() +
		", waterTimeSeconds * " + zw.x() +
		", waterTimeSeconds * " + zw.y() + ")";
}

String stretchUniform(String name, NoiseWave wave) {
	var s = wave.stretch();

	return "uniform.vec3.waterStretch" + name +
		"=vec3(" + s.scaleX() + "," + s.scaleY() + "," + s.shear() + ")";
}

String magnitudeUniform(String name, NoiseWave... waves) {
	String magnitudes = Arrays.stream(waves)
		.mapToDouble(NoiseWave::magnitude)
		.mapToObj(magnitude -> Float.toString((float) magnitude))
		.collect(Collectors.joining(","));

	return "uniform.vec" + waves.length + ".waterMagnitude" + name +
		"=vec" + waves.length + "(" + magnitudes + ")";
}

static final String header = """
# Generated by NoiseWaveIrisUniforms.java

#ifdef FREEZE_ANIMATION_TIMER
	variable.float.waterTimeSeconds=500.0
#else
	variable.float.waterTimeSeconds=frameTimeCounter
#endif
""";

void main() {
	IO.println(header);

	IO.println(scrollUniform("RippleAB",
		NoiseWave.RIPPLES[0].scroll(), NoiseWave.RIPPLES[1].scroll()));
	IO.println(scrollUniform("RippleCD",
		NoiseWave.RIPPLES[2].scroll(), NoiseWave.RIPPLES[3].scroll()));
	IO.println(scrollUniform("CrestAB",
		NoiseWave.CRESTS[0].scroll(), NoiseWave.CRESTS[1].scroll()));

	IO.println(stretchUniform("RippleA", NoiseWave.RIPPLES[0]));
	IO.println(stretchUniform("RippleB", NoiseWave.RIPPLES[1]));
	IO.println(stretchUniform("RippleC", NoiseWave.RIPPLES[2]));
	IO.println(stretchUniform("RippleD", NoiseWave.RIPPLES[3]));
	IO.println(stretchUniform("CrestA", NoiseWave.CRESTS[0]));
	IO.println(stretchUniform("CrestB", NoiseWave.CRESTS[1]));

	IO.println(magnitudeUniform("Ripple", NoiseWave.RIPPLES));
	IO.println(magnitudeUniform("Crest", NoiseWave.CRESTS));
}
