# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Temporary for now to avoid conflicting with other files, but I would like for
# fog.slang to not actually have to hardcode different fluid types at all
#
# TODO: Move fluid fog coloring here
uniform.int.isEyeInWaterFog=isEyeInWater

#if defined(VOXY)
	uniform.float.borderFogDistance=vxRenderDistance * 16.0
#elif defined(DISTANT_HORIZONS)
	uniform.float.borderFogDistance=dhRenderDistance
#else
	uniform.float.borderFogDistance=far
#endif

# Need to do this since on older Iris version (Iris 1.5), you cannot use the
# value of a define directly in a custom uniform expression.
#
# The strength of fog at noon. [0.0 0.25 0.33 0.5 0.66 0.75 1.0]
#if ATMOSPHERE_FOG_STRENGTH_NOON == 1.0
	variable.float.atmosphereFogStrengthNoon=1.0
#elif ATMOSPHERE_FOG_STRENGTH_NOON == 0.75
	variable.float.atmosphereFogStrengthNoon=0.75
#elif ATMOSPHERE_FOG_STRENGTH_NOON == 0.66
	variable.float.atmosphereFogStrengthNoon=0.66
#elif ATMOSPHERE_FOG_STRENGTH_NOON == 0.5
	variable.float.atmosphereFogStrengthNoon=0.5
#elif ATMOSPHERE_FOG_STRENGTH_NOON == 0.33
	variable.float.atmosphereFogStrengthNoon=0.33
#elif ATMOSPHERE_FOG_STRENGTH_NOON == 0.25
	variable.float.atmosphereFogStrengthNoon=0.25
#elif ATMOSPHERE_FOG_STRENGTH_NOON == 0.0
	variable.float.atmosphereFogStrengthNoon=0.0
#else
	variable.float.atmosphereFogStrengthNoon=0.5
#endif

# The division by 0.75 is to account for the 40 degree sun angle meaning that
# worldSunVector.y never actually gets to 1.0.
variable.float.noonFogProgress=clamp(worldSunVector.y / 0.75, 0.0, 1.0)

# We smooth the eye brightness ourselves as eyeBrightnessSmooth has odd jumps
# near 0 due to it being an integer instead of a float.
variable.float.eyeSkylightUnsmoothed=eyeBrightness.t / 240.0
uniform.float.eyeSkylight=smooth(eyeSkylightUnsmoothed, 10, 10)

# When in caves (ie, low skylight), disable atmosphere fog per:
# smoothstep(0.0, 0.25, eyeSkylight)
variable.float.fogInCave=clamp(eyeSkylight / 0.25, 0.0, 1.0)
variable.float.fogInCaveAdjustment=pow(fogInCave, 2.0) * (3.0 - 2.0 * fogInCave)

# Normal fog strength at 200 blocks and below
# Strength slightly boosted by 0.01 per block afterwards to counteract fog
# strength otherwise too rapidly decreasing with distance
variable.float.renderDistanceFogTweak=\
	1.0 + 0.01 * max(0.0, borderFogDistance - 200.0)
uniform.float.atmosphereFogCoefficient=renderDistanceFogTweak \
	* pow(0.60 / borderFogDistance, 3.0) \
	* mix(1.0, atmosphereFogStrengthNoon, noonFogProgress) \
	* fogInCaveAdjustment

# Smoothly transition between daytime and nighttime underwater fog. This is
# basically identical to the ambient lighting transition.
#
# This results in a rapid but smooth rampup from 0% to 100% as the sun/moon
# crosses the horizon and becomes the dominant source of light.
#
# A divisor of 0.05 with a 0.90 basis means that the transition occurs in +/-
# 0.3 degrees from the horizon.
uniform.float.dayUnderwaterFogFade=\
	pow(clamp(0.90 + worldSunVector.y / 0.05, 0.0, 1.0), 4)

# Since the fog is so dense, and is not synced with the sky color, we must
# manually adjust its intensity from day to night and as the camera enters
# underwater caves to maintain visibility.
variable.float.underwaterFogIntensity=\
	0.05 + 1.95 * dayUnderwaterFogFade * min(eyeSkylight * 2.0, 1.0)
uniform.vec3.underwaterFogColor=vec3( \
	underwaterFogIntensity * 0.03, \
	underwaterFogIntensity * 0.25, \
	underwaterFogIntensity * 1.00)

# Note that atmosphere fog is disabled in caves, so this only impacts border fog
uniform.vec3.caveFogColor=vec3(\
	0.02 * 0.33, \
	0.02 * 0.8 , \
	0.02 * 1.0 )
