# Steadfast is a fast and high-quality graphical overhaul for Minecraft (JE)
# Copyright (C) 2026 coderbot
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Mie preferred scattering direction value used by Bruneton. I was not
# immediately able to find where he got it from, but it looks fine to me.
variable.float.mieG=0.76

# To determine the light color, we ignore zero scattering and calculate
# single scattering in the direction of the light. Since the light vector and
# view vector are by definition the same, their dot product is a constant (1).
#
# Otherwise, these phase / scattering calculations are identical to normal
# atmosphere calculations (see minishita.glsl).
variable.float.lightMu=1.0
variable.float.lightCornetteShanks=3.0 / (8.0 * pi) \
	* ((1.0 - mieG * mieG) * (1.0 + lightMu * lightMu)) \
	/ ((2.0 + mieG * mieG) * pow(1.0 + mieG * mieG - 2.0 * mieG * lightMu, 1.5))
variable.float.lightRayleighPhase=3.0 / (16.0 * pi) * (1.0 + lightMu * lightMu)
variable.float.lightScatterMie=MIE_SCATTER_COEFFICIENT * lightCornetteShanks
variable.vec3.lightScatterRayleigh=vec3(\
	lightRayleighPhase * RAYLEIGH_SCATTER_COEFFICIENTS.r, \
	lightRayleighPhase * RAYLEIGH_SCATTER_COEFFICIENTS.g, \
	lightRayleighPhase * RAYLEIGH_SCATTER_COEFFICIENTS.b)

# Everything below here is the approximated (near-surface) Nishita transmittance
# calculation for sunlight. To avoid conflicts, all variables are prefixed with
# "st_". In this context, "worldDir" is identical to "worldSunVector".
#
# This is mostly a copy / port to custom uniforms of the relevant parts of
# SkyColor in minishita.glsl.

# The distance from the eye position to the edge of the atmosphere in the
# provided view direction.
#
# This is the same as RayIntersectUnitSphereBi(eyePos, worldDir), but
# specialized from the eye positioned at (0, EYE_HEIGHT_UNIT, 0) as we can
# assume in this function, and only caring about the forward intersection.
variable.float.st_od=EYE_HEIGHT_UNIT * worldSunVector.y
variable.float.st_oo=EYE_HEIGHT_UNIT * EYE_HEIGHT_UNIT
variable.float.st_sq=sqrt(st_od * st_od + (1.0 - st_oo))
variable.float.st_atmosphereDistance=st_sq - st_od

# We select two view sample positions along the view ray. Because typical
# reference implementations use upwards of 16 samples, the positioning
# of our two samples are important; hence, they are not uniformly placed.
#
# The first sample, within the lower atmosphere, primarily contributes to
# the color of the sky during daytime. The second sample, within the upper
# atmosphere, primarily contributes to the color of the sky in the early
# sunrise and late sunset.
#
# Finally, we calculate the height above the planet at each view sample
# point.
variable.vec3.st_samplePos1=vec3(\
	worldSunVector.x * (0.15 * st_atmosphereDistance), \
	worldSunVector.y * (0.15 * st_atmosphereDistance) + EYE_HEIGHT_UNIT, \
	worldSunVector.z * (0.15 * st_atmosphereDistance))
variable.vec3.st_samplePos2=vec3(\
	worldSunVector.x * (0.65 * st_atmosphereDistance), \
	worldSunVector.y * (0.65 * st_atmosphereDistance) + EYE_HEIGHT_UNIT, \
	worldSunVector.z * (0.65 * st_atmosphereDistance))
variable.float.st_vHeight1=sqrt(\
	st_samplePos1.x * st_samplePos1.x + \
	st_samplePos1.y * st_samplePos1.y + \
	st_samplePos1.z * st_samplePos1.z) - PLANET_RADIUS_UNIT
variable.float.st_vHeight2=sqrt(\
	st_samplePos2.x * st_samplePos2.x + \
	st_samplePos2.y * st_samplePos2.y + \
	st_samplePos2.z * st_samplePos2.z) - PLANET_RADIUS_UNIT

# Next, we calculate the change in optical depth caused by traveling
# through both sample points. To get the total optical depth, we integrate
# e^(-h/H)ds with respect to the path distance ("s").
#
# The change in optical depth at each sample point, with two sample points,
# is the path distance divided by the number of samples times the density
# ration, e^(-h/H), at the sample point.
variable.float.st_depthV1=(1.0 / 2.0) * st_atmosphereDistance * \
	exp(-st_vHeight1 / SCALE_HEIGHT_UNIT)
variable.float.st_depthV2=(1.0 / 2.0) * st_atmosphereDistance * \
	exp(-st_vHeight2 / SCALE_HEIGHT_UNIT)

# Typically, Nishita scattering involves sampling multiple (4-8) points
# along the light ray per each view sample. Because each view sample would
# then require multiple light samples in an inner loop, light samples can
# easily become the most computationally expensive part.
# 
# As it turns out, at least for for an Earth-like environment when viewing
# from near sea level, we can reduce the number of light samples to as
# little as one per view sample. However, when using a single sample, the
# selection of the sample point becomes significant.
#
# The light samples closer to the edge of the atmosphere contribute
# minimally to the optical depth compared to those deeper within the
# atmosphere. Mathematically, we can reason about this as the part of the
# e^-x curve farther away from the origin where it flattens out.
#
# Therefore, we should select a sample point (value of t) that is low
# (within the range 0 to 1). In my testing, t = 0.15 was acceptable, and it
# happens to match the first view sample point (used in SkyColor).
#
# We compute the change in optical depth identically to the view traces,
# but because we only have one sample along each light trace, there is no
# need to divide by the number of samples, as there is only one.

# Because sunlight is a special case where we are already tracing in the
# direction of the light, there is no need for the intersection calculation,
# as we can trivially compute it based on the distance we have already traveled
# in the direction of the light.
variable.float.st_lightDistance1=(1.0 - 0.15) * st_atmosphereDistance
variable.float.st_lightDistance2=(1.0 - 0.65) * st_atmosphereDistance

# From each sample point along the view ray, we then trace towards the
# light source, which similarly requires the distance to the edge of the
# atmosphere.
variable.vec3.st_lightSamplePos1=vec3(\
	worldSunVector.x * (0.15 * st_lightDistance1) + st_samplePos1.x, \
	worldSunVector.y * (0.15 * st_lightDistance1) + st_samplePos1.y, \
	worldSunVector.z * (0.15 * st_lightDistance1) + st_samplePos1.z)
variable.vec3.st_lightSamplePos2=vec3(\
	worldSunVector.x * (0.15 * st_lightDistance2) + st_samplePos2.x, \
	worldSunVector.y * (0.15 * st_lightDistance2) + st_samplePos2.y, \
	worldSunVector.z * (0.15 * st_lightDistance2) + st_samplePos2.z)
variable.float.st_lightHeight1=sqrt(\
	st_lightSamplePos1.x * st_lightSamplePos1.x + \
	st_lightSamplePos1.y * st_lightSamplePos1.y + \
	st_lightSamplePos1.z * st_lightSamplePos1.z) - PLANET_RADIUS_UNIT
variable.float.st_lightHeight2=sqrt(\
	st_lightSamplePos2.x * st_lightSamplePos2.x + \
	st_lightSamplePos2.y * st_lightSamplePos2.y + \
	st_lightSamplePos2.z * st_lightSamplePos2.z) - PLANET_RADIUS_UNIT

# We compute the change in optical depth identically to the view traces,
# but we only have one sample along each light trace.
variable.float.st_depthLight1=st_lightDistance1 * \
	exp(-st_lightHeight1 / SCALE_HEIGHT_UNIT)
variable.float.st_depthLight2=st_lightDistance2 * \
	exp(-st_lightHeight2 / SCALE_HEIGHT_UNIT)

# The stylized scale values mitigate some of the artifacts of our
# simplications, including selecting a single light sample at t = 0.15 an
# using the same scale height for Mie and Rayleigh scattering.
#
# These are not physically-based, but these were selected because I thought
# they looked nice.
#
# Technically, you are also supposed to add the two optical depth samples
# along the view vector. However, I did not like how it looked, and it
# probably does not work well because the two samples are so far apart.
variable.float.st_opticalDepth1=0.5 * st_depthLight1 + 0.05 * st_depthV1
variable.float.st_opticalDepth2=0.5 * st_depthLight2 + 3.0  * st_depthV2

# The final step of the integral is to sum up, along each view sample
# position, the density ratio, the change in path distance, and the actual
# transmittance contribution in the exponent.
#
# The density ratio times the change in path distance is the same as the
# optical depth contribution we already calculated for each view sample,
# hence why we re-use it here.
variable.vec3.st_tmSun1=vec3( \
	st_depthV1 * exp(st_opticalDepth1 * (-(RAYLEIGH_UNIT.r + MIE_UNIT))), \
	st_depthV1 * exp(st_opticalDepth1 * (-(RAYLEIGH_UNIT.g + MIE_UNIT))), \
	st_depthV1 * exp(st_opticalDepth1 * (-(RAYLEIGH_UNIT.b + MIE_UNIT))))
variable.vec3.st_tmSun2=vec3( \
	st_depthV2 * exp(st_opticalDepth2 * (-(RAYLEIGH_UNIT.r + MIE_UNIT))), \
	st_depthV2 * exp(st_opticalDepth2 * (-(RAYLEIGH_UNIT.g + MIE_UNIT))), \
	st_depthV2 * exp(st_opticalDepth2 * (-(RAYLEIGH_UNIT.b + MIE_UNIT))))
variable.vec3.st_tmSun=vec3( \
	st_tmSun1.r + st_tmSun2.r, \
	st_tmSun1.g + st_tmSun2.g, \
	st_tmSun1.b + st_tmSun2.b)

# Multiply transmittance and scattering to get the sunlight color.
variable.vec3.sunlightBaseMinishita=vec3( \
	st_tmSun.r * (lightScatterRayleigh.r + lightScatterMie), \
	st_tmSun.g * (lightScatterRayleigh.g + lightScatterMie), \
	st_tmSun.b * (lightScatterRayleigh.b + lightScatterMie))

variable.float.sunlightIntensity=27.5 * clamp(worldSunVector.y / 0.6, 0.0, 1.0)
uniform.vec3.sunlightMinishita=vec3( \
	sunlightIntensity * sunlightBaseMinishita.r, \
	sunlightIntensity * sunlightBaseMinishita.g, \
	sunlightIntensity * sunlightBaseMinishita.b)

# TODO: Everything below here isn't strictly related to the sunlight scattering
#       We might be able to move this stuff and deduplicate with "uncategorized"

# Moonlight
variable.vec3.moonlightBaseMinishita=vec3(0.5, 0.65, 1.0)
variable.float.moonlightIntensity=10.75 * mix(0.008, 0.024, nightVision) * \
	pow(max(0.0, -worldSunVector.y), 0.4)
uniform.vec3.moonlightMinishita=vec3( \
	moonlightIntensity * moonlightBaseMinishita.r, \
	moonlightIntensity * moonlightBaseMinishita.g, \
	moonlightIntensity * moonlightBaseMinishita.b)

# Contribution to lighting from the sky alone (skylight)
#
# TODO: Move remaining direct light color scattering to here.
variable.vec3.skyAmbientBase=vec3( \
	atmosphericAmbient.r + 0.25 * moonlightMinishita.r, \
	atmosphericAmbient.g + 0.25 * moonlightMinishita.g, \
	atmosphericAmbient.b + 0.25 * moonlightMinishita.b)

uniform.vec3.minAmbientMinishita=vec3(0.005 * 0.33, 0.005 * 0.8, 0.005 * 1.0)
variable.float.skyAmbientBaseLuminance=\
	0.2126 * skyAmbientBase.r + \
	0.7152 * skyAmbientBase.g + \
	0.0722 * skyAmbientBase.b
variable.float.skyAmbientRain=skyAmbientBaseLuminance * 0.6

# TODO: Fix sunlightBounce affecting moonlight
variable.float.sunlightBounce=0.125
variable.vec3.skyAmbientClear=vec3( \
	skyAmbientBase.r + sunlightBounce * \
		(sunlightMinishita.r + moonlightMinishita.r), \
	skyAmbientBase.g + sunlightBounce * \
		(sunlightMinishita.g + moonlightMinishita.g), \
	skyAmbientBase.b + sunlightBounce * \
		(sunlightMinishita.b + moonlightMinishita.b))

uniform.vec3.skyAmbientMinishita=vec3( \
	mix(skyAmbientClear.r, skyAmbientRain, rainStrength), \
	mix(skyAmbientClear.g, skyAmbientRain, rainStrength), \
	mix(skyAmbientClear.b, skyAmbientRain, rainStrength))

uniform.vec3.directLightSurfaceMinishita=vec3( \
	(1.0 - rainStrength) * (1.0 - sunlightBounce) * \
		(sunlightMinishita.r + moonlightMinishita.r), \
	(1.0 - rainStrength) * (1.0 - sunlightBounce) * \
		(sunlightMinishita.g + moonlightMinishita.g), \
	(1.0 - rainStrength) * (1.0 - sunlightBounce) * \
		(sunlightMinishita.b + moonlightMinishita.b))
